version: "2"
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 5775:5775
      - 6831:6831
      - 6832:6832
      - 5778:5778
      - 16686:16686
      - 14268:14268
  web:
    build: .
    container_name: "app"
    ports:
      - 1234:1234
    depends_on:
      - jaeger