version: "2"
services:
  mongo:
    image: mongo:latest
    container_name: "app_db"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
  web:
      build: .
      container_name: "app"
      ports:
        - 1234:1234
      environment:
        - DOCKER_DB=mongo
      links:
        - mongo
      depends_on:
        - mongo